#!/bin/bash
# -*- sh -*-

load() { ## ## reload environment ## shell
 . $Lure/etc/bashrc
}
install() { ## ## install LURE (need only be run once) ## install
  cd $Lure
  if [ "$(uname)" == "Darwin" ]; then
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
  if [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
     cat <<-EOF
    
  Have you run the choco install commands? See https://github.com/chocolatey/choco/wiki/Installation

  EOF
  fi
  if [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
     cat <<-EOF
    
  Have you run the choco install commands? See https://github.com/chocolatey/choco/wiki/Installation

  EOF
  fi
  sudo easy_install Pygments
  for f in lua luajit vim git make ctags gawk mc htop ranger asciiquarium cmatrix ; do
    if which $f; then true; else 
     if [ "$(uname)" == "Darwin" ]; then
        brew install $f
     elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
        sudo apt-get install $f
     elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
        choco install $f
     elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
        choco install $f
     fi 
   fi
  done
  if  [ ! -d "$HOME/.vim/bundle/Vundle.vim" ]; then
    git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
    vim -u "$Lure/etc/vimrc" -c 'PluginInstall' -c 'qa!'
  fi
  if [ ! -f "$Lure/.gitignore" ]; then
     cat <<EOF > "$Lure/.gitignore"
#vimstuff
[._]*.s[a-w][a-z]
[._]s[a-w][a-z]
*.un~
Session.vim
netrwhist
*~
# doc stuff
docs
locco
# mac stuff
.DS_Store
# testing stuff
_allok.lua
EOF
  fi
  if [ ! -d "$Lure/etc/locco" ]; then
    git clone https://github.com/rgieseke/locco etc/locco
  fi
  gitting
  timm
}
doco() { ## ## generate html doco files ## shell
   if [ ! -d "$Lure/../info" ]; then
     echo "Missing target repo: [info]"
     echo "I suggest you:"
     echo "   cd $Lure/.."
     echo "   git clone http://github.com/lualure/info"
   else  
     cd $Lure/etc/locco
     (echo "-- # Index"
     echo ""
     echo "(Auto-generated. Do not edit.)"
     echo ""
     for i in ${Lure}/lib/*.lua; do
       f=$(basename $i '.lua')
       l="$(basename $i '.lua').html"
       echo "-- - [$f]($l) "
     done
     echo "") > $Lure/lib/index.lua
     for i in ../../lib/*.lua; do
       ./locco.lua $i
     done
     cd $Lure
     cd $Lure/../info/docs
     cp $Lure/lib/docs/* .
     git add *
     make
     cd $Lure
   fi 
}
vi() { ## FILE ## edit files using the LURE config stuff ## shell
    vim -u "$Lure/etc/vimrc" $*
    echo "Done!"
}
ok() { ## STEM ## shorthand for lua STEMok.lua ## shell
  l ${1}ok.lua
}
show() { ## FUN ## display definition of FUN ## shell
  type $1
}
oks() { ## ## run all the Xok.lua files ## shell
  ls ${Lure}/tests/*ok.lua | 
  grep -v _allok |
  gawk '{sub(/.lua/,"",$0) 
         sub(/^.*\//,"",$0)
         printf(" require \"%s\";\n",$0)}' > ${Lure}/tests/_allok.lua
  cd ${Lure}/tests
  l _allok.lua
  rm  _allok.lua
  cd $Lure
}
bye() { ## ## push all to on-line repo ## git
  gitting
	git status
	git commit -am "saving"
 git push origin master
}
hi() { ## ## pull updates from on-line repo ## git
  gitting
	git push origin master
}
gitting() {
	git config --global credential.helper cache
	git config credential.helper 'cache --timeout=3600'
	git config --global push.default simple
}
timm() { ## ## Private: sets up this repo for timm ## install
	git config --global user.name "Tim Menzies"
	git config --global user.email tim.menzies@gmail.com
}
legal() { ## ## show copyright notice ## misc
  cat $Lure/LICENSE.md
}
help() { ## ## show help ## misc
  echo "${blue}"
  echo "Options:"
  grep '##' $Lure/etc/bashrc | 
  sort -t\# -k 7  | 
  grep -v 'grep' |
  gawk '  function trim(x) {
            sub(/^[ \t]*/,"",x)
            sub(/[ \t]*$/,"",x)
            return x
          }
           BEGIN  { FS="##" }  
          /BEGIN/ { next    }
          { for(i=1;i<=NF;i++)
               $i=trim($i)
            pad="         "
            pre=  $NF==last ? pad : toupper($NF)":\n" pad
            last=$NF 
            gsub(/[(){]/,"",$1)
            opts= NF==4 ? $2 : ""
            text= NF==4 ? $3 : $2
	    if ($3)
	       printf("%s%-8s%-10s%s\n",pre,$1,opts,text)}
              '
  echo -n "${white}"
}
quit() { ## ## exit ## shell
  exit
}
make() { ## [OPTS] ## run any Makefile at the root of this repo ## shell
  root=$(git rev-parse --show-toplevel)
  if [ -n "$root" ]; then
    ( cd $root; _make1 $*)
  else
    /usr/bin/make $*
  fi
}
_make1() {
    if [ -f Makefile ]; then
        echo "My making..."
        /usr/bin/make $*
        return 0
    fi
    echo "nothing to do"
}
_twins1() {
cat <<EOF
-- # $1 : $2


------------------------------------------------------

require "show"
local the=require "config"
	
EOF
}
twins() { ## STEM ## makes STEM.lua and unit test file STEMok.lua ## shell
  f=$(basename $1 ".lua")
  if [ ! -f "$Lure/lib/${f}.lua" ]; then 
	   _twins1 $f utilities  > $Lure/lib/${f}.lua
  fi
  if [ ! -f "$Lure/tests/${f}ok.lua" ]; then
	   _twins1 ${f}ok "unit tests for $f" > $Lure/tests/${f}ok.lua
	   git add $Lure/tests/${f}ok.lua
	   cat <<-EOF >> $Lure/tests/${f}ok.lua
	local o=require "tests"	
	local r=require "random"
	local x=require "$f"
 
	local function _test1()
        	assert(true)
	end

	r.seed(1)
	o.k{_test1}
	EOF
  fi
  git add $Lure/lib/${f}.lua
  git add $Lure/tests/${f}ok.lua
  wc $Lure/lib/${f}.lua $Lure/tests/${f}ok.lua
}
norman() { ## ## about Norman Vaughan ## misc
  cat<<-EOF | fmt -60
  
	"Dream big and dare to fail."   
	 -- Norman Vaughan

	Norman Vaughan was born on December 19, 1905, in Salem, Massachusetts,
	as the son of a wealthy leather tanner and shoe manufacturer.

	In his youth, he became fascinated by tales of early-century polar
	explorers. He dropped out of Harvard in 1928 when he heard that
	Admiral Richard E. Byrd was organizing an expedition to Antarctica.
	Admiral Byrd accepted him on the 1928–1930 expedition, eventually
	naming a mountain on the continent in his honor. 
	In 1994, at the age of 88, Vaughan participated in an expedition
	to climb the 10,302 ft (3,150 m) Mount Vaughan. 

	In 1932, he competed in the Winter Olympics in Lake Placid, New
	York, in the sprint mushing demonstration sport.

	During World War II, Vaughan was employed by U.S. Army Air Forces
	Search and Rescue as a dogsled driver, attaining the rank of
	colonel and engaging in many rescue missions in Greenland. 

	Norman Vaughan moved to Alaska at the age of 68. Bankrupt and
	divorced, he rebuilt his life, competing in 13 Iditarod races and
	"crashing" the Presidential Inauguration parade in 1977, bringing
	sled dogs to represent his adopted state. In 1981 and 1985, he
	and his Alaskan contingent formally participated in the parade.
	He also had a mountain named after him in the Antarctic.

	He is survived by his fourth wife, the former Carolyn Muegge, who
	has also raced in the Iditarod, and a son and daughter from his
	earlier marriages. On the celebration of his 100th birthday on
	December 18, 2005, surrounded by over 100 friends and family, he
	had champagne, his first drink of liquor in his life, after
	promising his mother he wouldn't drink until he was 100. Several
	days later, he died in the Providence Alaska Medical Center in
	Anchorage at around 10:30 AM on December 23, 2005. His wife and
	some close friends were with him.
	EOF
}
here() { cd $1; basename "$PWD"; }

l() { ## FILE ## call "lua FILE" in this environment (.lua extension optional) ## shell
  f=$(basename $1 .lua).lua
  shift
  for d in lib tests; do
    if [ -f "$Lure/$d/$f" ]; then
      LUA_PATH="$Lure/lib/?.lua;$Lure/tests/?.lua;;" \
        $(which luajit) $Lure/$d/$f "$*"
      return 0
    fi
  done
  echo "not found $f"
}
setup() {
  alias ls='ls -G'
  export LESS='-R'
  export LESSOPEN='|$Lure/etc/lessfilter %s'
  Tag="LURE"
  _c1="\[\033[01;32m\]"
  _c2="\[\033[01;34m\]"
  _c3="\[\033[31m\]"
  _c6="\033[33m"
  _c5="\[\033[35m\]$"
  _c0="\[\033[00m\]"
  _c7="[\033]01;19\]"
  red=$(tput setaf 1)
  blue=$(tput setaf 6)
  ltyl=$(tput setaf 11)
  white=$(tput setaf 15)
}
news1() {
  while true; do
    clear
     curl --silent "$1" | grep -E '(title>|description>)' |  
     sed  -n '4,100p' | 
     sed -e 's/<title>/\
/' -e 's/<\/title>//' -e 's/<description>/ /'  -e 's/<\/description>//' \
     -e 's/\&.*//' -e 's/^[ \\\t]*//'
    sleep 60
  done
}
news() {
    news1 'http://feeds.reuters.com/reuters/topNews'
}

promptcom() {
  PROMPT_COMMAND='echo  -ne "${_c6}${Tag}\033]0;$(here ../..)/$(here ..)/$(here .)\007";PS1="${_c1}(\A) $(here ../..)/$_c2$(here ..)/$_c3$(here .) ${_c6}\!>${_c0}\e[m "'
} 
banner() {
  echo -n "${ltyl}" 
  cat <<'EOF'
                                 _H_     | LURE v1.00
                                /___\    | https://github.com/lualure/info
                                \888/    |
~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~U~^~| "Dream big and dare to fail."
                   ~              |      |  -- Norman Vaughan
   ~                        o     |      |
             ___        o         |      | "The charm of fishing is that it is 
    _,.--,.'`   `~'-.._    O      |      |  the pursuit of what is elusive but 
   /_  .-"      _   /_\'.         |   ~  |  attainable, a perpetual series of 
  .-';'       (( `  \0/  `\       #      |  occasions of hope." 
 /__;          ((_  ,_     |      #      |  -- Jack Nicklaus
 .-;                  \_   /  #  _#,     |
/  ;    .-' /  _.--""-.\`~`   `#(('\\    | "There are always new places to go 
;-';   /   / .'                  )) \\   |  fishing. For any fisherman (sic), 
    ; /.--'.'                   ((   ))  |  there's always a new place, always
     \     |        ~            \\ ((   | a new horizon." 
      \    |                      )) `   |  -- John Buchan
~      \   |                      `      |
        \  |                             | "Gone fishin', for a new idea." 
   jgs  .` `""-.                         |  -- Tim Menzies
      .'        \         ~              
      |    |\    |
      \   /  '-._|
       \.'
EOF
echo -n "${white}"
}
##########################################################
# start up actions
setup
promptcom
if [ -f "$HOME/.config/lure/config" ]; then
  . "$HOME/.config/lure/config"
fi
banner
help

